"""Render ts_v13.py into the team workbook (.xlsx) and 01-intake/scenarios.yaml.

    pip install openpyxl pyyaml
    python build_workbook.py
"""
import os
import re

import yaml
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

import ts_v13 as d

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "EAINT-12341_Test_Case_v1.3.xlsx")
YAML_OUT = os.path.join(HERE, "..", "01-intake", "scenarios.yaml")

F = "Arial"
THIN = Side(style="thin", color="808080")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
HDR = PatternFill("solid", fgColor="D9D9D9")
SEC = PatternFill("solid", fgColor="BFBFBF")
YEL = PatternFill("solid", fgColor="FFFF00")
RED = PatternFill("solid", fgColor="FFC7CE")
CYAN = PatternFill("solid", fgColor="DDEBF7")
TOP = Alignment(wrap_text=True, vertical="top")
MID = Alignment(wrap_text=True, vertical="center", horizontal="center")


def cell(ws, ref, value, bold=False, fill=None, align=TOP, border=True, size=10, color=None):
    c = ws[ref]
    c.value = value
    c.font = Font(name=F, size=size, bold=bold, color=color)
    c.alignment = align
    if fill:
        c.fill = fill
    if border:
        c.border = BOX
    return c


def widths(ws, ws_widths):
    for i, w in enumerate(ws_widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def table(ws, start_row, headers, rows, col_widths=None):
    for j, h in enumerate(headers, start=1):
        cell(ws, f"{get_column_letter(j)}{start_row}", h, bold=True, fill=HDR, align=MID)
    for i, r in enumerate(rows, start=start_row + 1):
        for j, v in enumerate(r, start=1):
            cell(ws, f"{get_column_letter(j)}{i}", v)
    if col_widths:
        widths(ws, col_widths)
    ws.freeze_panes = ws[f"A{start_row + 1}"]
    return start_row + len(rows)


wb = Workbook()

# ── Sheet 1: test scenarios in the team layout ──────────────────────────────
ws = wb.active
ws.title = "EAINT-12341"
COLS = ["TS No.", "Business Type", "No. of Directors / Business Owners", "Nationality of Directors / Business Owners",
        "Expected Email(s)", "Steps", "Expected Result", "Remarks", "Chain / Test Data", "Requirement",
        "Priority (proposed)", "Test Type", "Actual Result", "Status", "Evidence"]
widths(ws, [15, 22, 18, 18, 22, 56, 64, 48, 16, 18, 12, 16, 40, 12, 24])

header = [
    ("Ticket", "EAINT-12341 — [eAuto-BackEnd & UCD] Replace Approved Application Email with New Emails to UCD and RHB Support"),
    ("Link", "https://mfservices.atlassian.net/browse/EAINT-12341"),
    ("SRD", d.SRD + " — active: REQ-001, 002, 005 (updated), 006, 007, 008, 009. REMOVED: REQ-003, REQ-004. "
            "Email template: EMAIL TEMPLATE - RHB ACCOUNT OPENING V3.0 (29.09.2026). Letter: Appointment Letter Template v2.0 (18.09.2026)."),
    ("Test Objective", "To verify that upon Application approval the system replaces the existing approved application email with 2 emails: "
                       "(1) ONE combined RHB Account Registration Guideline email (Email Template 1 — online and branch options) sent to every UCD "
                       "regardless of the number of directors / business owners and their nationality, with the Appointment Letter attached; and "
                       "(2) the Appointment Letter email to RHB Support (Email Template 3) with the UCD and apply@eauto.my copied and the generated "
                       "Appointment Letter attached."),
    ("Trigger", "Application approval only. Pre-Application approval, Submitted and Revert to UCD are not triggers."),
    ("Affected Pages", "1. BackOffice > Application — Application Approval (triggers the emails).\n"
                       "2. Email — RHB Account Registration Guideline (Email Template 1, combined) → UCD, CC apply@eauto.my, Appointment Letter attached.\n"
                       "3. Email — Appointment Letter (Email Template 3) → BIS.Support@rhbgroup.com, CC UCD + apply@eauto.my, Appointment Letter attached.\n"
                       "4. Appointment Letter document — generated by the system (SRD §2.2.5.2).\n"
                       "Not changed, exercised by the chain: UCD Pre-Application, BO Pre-Application approval, UCD Application, BO Registration Document (regression)."),
    ("v1.3 Change", "Email Template 2 and the guideline determination by director count / nationality are REMOVED. The v1.1 template-selection cases "
                    "(E2E1–E2E12) are retired — see 'Retired (v1.1)'. Coverage of company structure is now a 'same template regardless' check (Section B)."),
    ("Execution Model", "Each chain (CH1–CH6, 'Test Data & Chains' sheet) is run by the Playwright spec cr/EAINT-12341/03-spec/onboarding-chain.spec.ts up to the "
                        "approval. Emails and the letter are verified MANUALLY in Mailtrap against the expected values the run prints. One chain feeds many TS."),
    ("Verification", "All emails verified in Mailtrap. No live email may reach BIS.Support@rhbgroup.com during testing (Q-17)."),
    ("Note", "The SRD calls the portal BackEnd; the system name is BackOffice (BO)."),
    ("Legend", "Yellow TS No. — needs a chain (test data) executed first.   |   Red TS No. — expected result pending confirmation (see Open Questions).   |   "
               "Priority is a QA proposal — confirm with the QA Lead."),
]
for i, (k, v) in enumerate(header, start=1):
    cell(ws, f"A{i}", k, bold=True)
    ws.merge_cells(f"B{i}:O{i}")
    cell(ws, f"B{i}", v)
    ws.row_dimensions[i].height = 15 * max(1, min(6, len(v) // 160 + v.count("\n") + 1))

HR = len(header) + 2
for j, h in enumerate(COLS, start=1):
    cell(ws, f"{get_column_letter(j)}{HR}", h, bold=True, fill=HDR, align=MID)
ws.row_dimensions[HR].height = 45
ws.freeze_panes = ws[f"B{HR + 1}"]

chain_by_id = {c["id"]: c for c in d.CHAINS}
row = HR + 1
section = None
first_ts_row = row
for t in d.TS:
    if t["section"] != section:
        section = t["section"]
        ws.merge_cells(f"A{row}:O{row}")
        cell(ws, f"A{row}", section, bold=True, fill=SEC)
        row += 1
    ch = chain_by_id.get(t["chain"].split(",")[0].split(" ")[0])
    if ch and "," not in t["chain"] and "every" not in t["chain"]:
        btype, cnt, nat = ch["btype"], ch["count"], ch["nationality"]
    else:
        btype, cnt, nat = "Per chain", "Per chain", "Per chain"
    exp_email = {"A": "Email Template 1 (combined)", "B": "Email Template 1 (combined)", "C": "Email Template 3",
                 "D": "Appointment Letter", "E": "—"}[t["section"][0]]
    values = [t["id"], btype, cnt, nat, exp_email, t["pre"] + "\n\n" + t["steps"], "Ensure:\n" + t["expected"],
              t["title"] + ("\n\n" + t["remarks"] if t["remarks"] else ""), t["chain"], t["req"], t["prio"], t["type"],
              "", "Not Run", ""]
    for j, v in enumerate(values, start=1):
        ref = f"{get_column_letter(j)}{row}"
        if j == 1:
            cell(ws, ref, v, bold=True, fill=RED if t["red"] else YEL, align=MID)
        else:
            cell(ws, ref, v)
    ws.row_dimensions[row].height = min(409, 13 * max(values[5].count("\n"), values[6].count("\n"), 4) + 40)
    row += 1
last_ts_row = row - 1

dv = DataValidation(type="list", formula1='"Not Run,Pass,Fail,Blocked,N/A"', allow_blank=True)
ws.add_data_validation(dv)
dv.add(f"N{first_ts_row}:N{last_ts_row}")

# ── Sheet 2: summary (formulas) ──────────────────────────────────────────────
sm = wb.create_sheet("Summary")
widths(sm, [28, 14])
cell(sm, "A1", "Execution summary — counts from sheet 'EAINT-12341' column N", bold=True, border=False)
rng_n = f"'EAINT-12341'!$N${first_ts_row}:$N${last_ts_row}"
rng_k = f"'EAINT-12341'!$K${first_ts_row}:$K${last_ts_row}"
rng_a = f"'EAINT-12341'!$A${first_ts_row}:$A${last_ts_row}"
cell(sm, "A3", "Metric", bold=True, fill=HDR)
cell(sm, "B3", "Count", bold=True, fill=HDR)
rows = [("Total test scenarios", f'=COUNTIF({rng_a},"12341_TS*")')]
for s in ["Not Run", "Pass", "Fail", "Blocked", "N/A"]:
    rows.append((f"Status = {s}", f'=COUNTIF({rng_n},"{s}")'))
for p in ["High", "Medium", "Low"]:
    rows.append((f"Priority = {p}", f'=COUNTIF({rng_k},"{p}")'))
rows.append(("Executed %", "=IF(B4=0,0,(B6+B7)/B4)"))
for i, (k, v) in enumerate(rows, start=4):
    cell(sm, f"A{i}", k)
    cell(sm, f"B{i}", v)
sm[f"B{3 + len(rows)}"].number_format = "0.0%"

# ── Sheet 3: change analysis ────────────────────────────────────────────────
ca = wb.create_sheet("Change Analysis v1.1-v1.3")
cell(ca, "A1", "SRD change analysis v1.1 (17.09) → v1.2 (24.09) → v1.3 (29.09) and impact on the test design", bold=True, border=False)
table(ca, 3, ["SRD Version", "Requirement / Section", "Change", "Test Impact"], d.CHANGES, [12, 22, 70, 70])

# ── Sheet 4: traceability ───────────────────────────────────────────────────
tr = wb.create_sheet("Traceability")
cell(tr, "A1", "Requirement → Test Scenario traceability (SRD v1.3)", bold=True, border=False)
rows = []
for rid, item, status, ac in d.REQS:
    short = rid.replace("EAINT-12341-", "")
    covered = [t["id"] for t in d.TS if re.search(rf"\b{short}\b", t["req"])]
    if "REMOVED" in status:
        covered_txt = "— (removed). Negative proof: TS07, TS08 (no Branch-only email)"
    else:
        covered_txt = ", ".join(covered)
    rows.append((rid, item, status, ac, covered_txt, f"=COUNTIF('EAINT-12341'!$J${first_ts_row}:$J${last_ts_row},\"*{short}*\")"))
table(tr, 3, ["Requirement ID", "Item", "Status in v1.3", "Acceptance Criteria (summary)", "Test Scenarios", "# TS referencing"],
      rows, [22, 20, 20, 60, 40, 12])

# ── Sheet 5: test data & chains ─────────────────────────────────────────────
td = wb.create_sheet("Test Data & Chains")
cell(td, "A1", "Chains (test data). Each chain consumes one real company (one company, one use — company-ledger.json).", bold=True, border=False)
rows = []
for c in d.CHAINS:
    used_by = ", ".join(t["id"] for t in d.TS if c["id"].split("_")[1] in t["chain"])
    rows.append((c["id"], c["btype"], c["count"], c["nationality"], c["stop"], c["purpose"], c["data"], used_by,
                 "", "", "", "", ""))
table(td, 3, ["Chain", "Business Type", "Directors / Owners", "Nationality", "Runs Until", "Purpose", "Test Data Needed",
              "Used by TS", "Company (ROC/ROB/LLP) assigned", "Pre-Application No", "Application No", "UCD Email", "Run Date / Result"],
      rows, [12, 22, 16, 16, 18, 50, 46, 28, 22, 18, 16, 30, 18])
n = 3 + len(rows) + 2
notes = [
    "Fill columns I–M after each run from the run log's READY FOR MANUAL EMAIL CHECK block.",
    "Spent companies from the v1.1 attempts (do not reuse): IP0581553-U (E2E1), 003270488-X (E2E2), 1267419-A (E2E6). See company-ledger.json.",
    "Admin In Charge and Director in Charge use DIFFERENT name / mobile / email on purpose (Q-04): the emails then show which source the system uses.",
]
for i, t in enumerate(notes):
    cell(td, f"A{n + i}", t, border=False)

# ── Sheet 6: expected templates (verbatim) ──────────────────────────────────
et = wb.create_sheet("Expected Templates")
cell(et, "A1", "Expected content, verbatim from SRD v1.3 (§2.2.4.1, §2.2.5.1, §2.2.5.2)", bold=True, border=False)
rows = [
    ("Email Template 1 — Sender", "Pending confirmation from Operations (do not assert)."),
    ("Email Template 1 — Recipient", "To: Approved UCD email address captured in the Application.\nCC: apply@eauto.my"),
    ("Email Template 1 — Subject", d.T1_SUBJECT + "\nE.g.: RHB Online / Branch Account Opening - NA50000802 - ABC Motors Sdn Bhd"),
    ("Email Template 1 — Body", d.T1_BODY),
    ("Email Template 1 — [RHB Online Registration Link]", d.RHB_LINK),
    ("Email Template 3 — Sender", "Pending confirmation from Operations (do not assert)."),
    ("Email Template 3 — Recipient", "To: BIS.Support@rhbgroup.com\nCC: Approved UCD email address captured in the Application, apply@eauto.my"),
    ("Email Template 3 — Subject", d.T3_SUBJECT + "\nE.g.: Approved eAuto Registration - ABC Motors Sdn Bhd - 202401234567"),
    ("Email Template 3 — Body", d.T3_BODY),
]
rows += [(f"Appointment Letter — {k}", v) for k, v in d.LETTER]
rows += [(f"Letter field {k}", v) for k, v in d.LETTER_FIELDS]
end = table(et, 3, ["Element", "Expected"], rows, [36, 110])
for r in range(4, end + 1):
    lines = str(et[f"B{r}"].value).count("\n") + len(str(et[f"B{r}"].value)) // 120 + 1
    et.row_dimensions[r].height = min(409, 13 * lines + 6)
cell(et, f"A{end + 2}", "Differences found between sources", bold=True, border=False)
diffs = [
    ("Template doc V3.0 vs SRD §2.2.4.1", "Template doc has no subject, sender, recipients or signature block; body text otherwise identical. → Q-01, Q-02."),
    ("Letter title", "SRD 'SDN. BHD. PLATFORM' vs template .docx 'SDN. BHD.PLATFORM'. → Q-10."),
    ("Sample letter brackets", "Sample keeps [ ] around Our Ref and the registration no. (recipient block, Clause 1). → Q-07."),
]
for i, (k, v) in enumerate(diffs, start=end + 3):
    cell(et, f"A{i}", k)
    cell(et, f"B{i}", v)

# ── Sheet 7: open questions ─────────────────────────────────────────────────
oq = wb.create_sheet("Open Questions")
cell(oq, "A1", "Open questions — raise with BA / Dev before execution sign-off", bold=True, border=False)
table(oq, 3, ["#", "Question", "Impact / interim handling", "Blocks", "Ask", "Status", "Answer", "Answered by / date"],
      d.QUESTIONS, [7, 70, 42, 18, 18, 10, 40, 18])

# ── Sheet 8: retired v1.1 cases ─────────────────────────────────────────────
rt = wb.create_sheet("Retired (v1.1)")
cell(rt, "A1", "v1.1 workbook cases and where they went under SRD v1.3", bold=True, border=False)
table(rt, 3, ["v1.1 TS No.", "v1.1 Scenario", "v1.3 Disposition"], d.RETIRED, [16, 40, 80])

for sheet in wb.worksheets:
    sheet.sheet_view.zoomScale = 90
wb.save(OUT)
print("wrote", OUT)

# ── scenarios.yaml (machine-readable mirror) ────────────────────────────────
doc = {
    "meta": {
        "ticket": "EAINT-12341",
        "source_srd": d.SRD,
        "source_email_template": "EMAIL TEMPLATE - RHB ACCOUNT OPENING_v3.0_20260929.docx",
        "source_letter_template": "eAuto_UCD_Appointment_Letter_Template_v2.0_20260918.docx",
        "workbook": "02-plan/EAINT-12341_Test_Case_v1.3.xlsx",
        "generated_by": "02-plan/build_workbook.py from 02-plan/ts_v13.py — do not hand-edit",
        "superseded": "scenarios.v1.1.yaml (SRD v1.1 intake, kept for history)",
    },
    "requirements": [{"id": r[0], "item": r[1], "status": r[2], "acceptance": r[3]} for r in d.REQS],
    "chains": d.CHAINS,
    "cases": [{k: t[k] for k in ("id", "section", "chain", "req", "title", "type", "prio", "pre", "steps", "expected", "remarks", "red")}
              for t in d.TS],
    "open_questions": [{"id": q[0], "question": q[1], "interim": q[2], "blocks": q[3], "ask": q[4], "status": q[5]} for q in d.QUESTIONS],
    "retired_v1_1": [{"id": r[0], "scenario": r[1], "disposition": r[2]} for r in d.RETIRED],
}
with open(YAML_OUT, "w", encoding="utf-8") as fh:
    fh.write("# EAINT-12341 — SRD v1.3 cases. GENERATED by 02-plan/build_workbook.py — edit 02-plan/ts_v13.py instead.\n")
    yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=120)
print("wrote", YAML_OUT)
